name: BranchCheck

on:
  pull_request:
    branches: [ "main" ]

jobs:
  validate:
    if: startsWith(github.head_ref, 'feature/') || startsWith(github.head_ref, 'hotfix/')
    runs-on: ubuntu-latest  
    steps:
      - run: echo "Validate..."
