name: BranchCheck

on:
  pull_request:
    branches: [ "main" ]

jobs:
  BanchNameCheck:
    runs-on: ubuntu-latest  
    steps:
      - if: startsWith(github.head_ref, 'feature/') || startsWith(github.head_ref, 'hotfix/')
      - uses: actions/github-script@v3
        with:
          script: |
            core.setFailed('Coverage test below tolerance')
      - run: echo "Validate..."
